import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'theme/app_theme.dart';
import 'routes/app_router.dart';
import 'screens/splash/splash_screen.dart';
import 'screens/onboarding/onboarding_screen.dart';
import 'screens/auth/login_screen.dart';
import 'widgets/root_shell.dart';
import 'services/auth_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Requires firebase_options.dart generated by running
  // `flutterfire configure` against your own Firebase project.
  // Uncomment once that file exists:
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const JmcInnovatorsApp());
}

class JmcInnovatorsApp extends StatelessWidget {
  const JmcInnovatorsApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'JMC Innovators Learning Platform',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.dark,
      routes: AppRouter.routes,
      home: const _AppFlow(),
    );
  }
}

/// Drives splash -> onboarding (first launch only) -> auth -> home,
/// persisting the "onboarding seen" flag with SharedPreferences.
class _AppFlow extends StatefulWidget {
  const _AppFlow();

  @override
  State<_AppFlow> createState() => _AppFlowState();
}

enum _Stage { splash, onboarding, auth, home }

class _AppFlowState extends State<_AppFlow> {
  _Stage _stage = _Stage.splash;
  final _auth = AuthService();

  Future<void> _afterSplash() async {
    final prefs = await SharedPreferences.getInstance();
    final seenOnboarding = prefs.getBool('seen_onboarding') ?? false;
    if (!seenOnboarding) {
      setState(() => _stage = _Stage.onboarding);
      return;
    }
    _goToAuthOrHome();
  }

  void _goToAuthOrHome() {
    // Firebase.initializeApp must have run for currentUser to be reliable;
    // until firebase_options.dart is wired in, this always falls through
    // to the login screen.
    if (_auth.currentUser != null) {
      setState(() => _stage = _Stage.home);
    } else {
      setState(() => _stage = _Stage.auth);
    }
  }

  Future<void> _finishOnboarding() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('seen_onboarding', true);
    _goToAuthOrHome();
  }

  @override
  Widget build(BuildContext context) {
    switch (_stage) {
      case _Stage.splash:
        return SplashScreen(onFinished: _afterSplash);
      case _Stage.onboarding:
        return OnboardingScreen(onDone: _finishOnboarding);
      case _Stage.auth:
        return LoginScreen(onAuthenticated: () => setState(() => _stage = _Stage.home));
      case _Stage.home:
        return const RootShell();
    }
  }
}
